[project]
name = "documentation-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "black>=26.5.1",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "langchain>=1.4.1",
    "langchain-chroma>=1.1.0",
    "langchain-ollama>=1.1.0",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "nltk>=3.10.3",
    "ollama>=0.6.2",
    "pinecone-client>=6.0.0",
    "streamlit>=1.64.0",
    "streamlit-chat>=0.1.1",
    "tiktoken>=0.14.0",
    "tqdm>=4.70.1",
    "truststore>=0.10.4",
    "unstructured>=0.27.6",
    "uvicorn>=0.53.0",
]
